AllCops:
  Exclude:
    - '*.md'
    - 'Gemfile'
    - 'Gemfile.lock'
    - db/schema.rb
    - config/**/*.rb
    - script/rails

Layout/IndentationWidth:
  Enabled: false

Metrics/LineLength:
  Max: 130
  Exclude:
    - '*.gemspec'

Style/RescueModifier:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*.rb'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

# These may break ruby 1.9 support:

Layout/IndentHeredoc:
  Enabled: false

Style/HashSyntax:
  Enabled: false